### ISSUE TITLE
Provide a method to initialize/set the value of a Sum.

### ISSUE THREAD

**Issue by rfoxkendo** [davehadley/ndhistogram#30]
Provide a method to set the value of a Sum value to any desired value.
The use case for this is to provide for restoration of a  histogram from e.g. file and allow for subsequent processing to continue to increment the histogram.

Two potential approaches:

*   Implement From<T> - to do this properly really means implementing that for all Value types.  Which is a bit of a bother.
*   Implement FillWith for Sum which is 
    1.  More natural.
    2.  Better confined.

**Comment by davehadley** [comment]
@rfoxkendo I don't see any problem with implementing `FillWith` for `Sum` if the inner type also implements `FillWith`. If you create a pull request we can add this.

> The use case for this is to provide for restoration of a histogram from e.g. file and allow for subsequent processing to continue to increment the histogram.

For serialization / deserialization to / from a file I expected that [serde](https://serde.rs/). would be used in most cases. Do you have a use case where you can't use serde?

**Comment by rfoxkendo** [comment]
Sorry a bit new to using GitHub and did not realize I could make a pull request across forks of the repository.  Done.  There’s now a pull request for you. Ron. Sent from Mail for Windows From: David HadleySent: Wednesday, May 17, 2023 3:57 AMTo: davehadley/ndhistogramCc: Ron Fox; MentionSubject: Re: [davehadley/ndhistogram] Provide a method to initialize/set the value of a Sum. (Issue ***@***.*** I don't see any problem with implementing FillWith for Sum if the inner type also implements FillWith. If you create a pull request we can add this.The use case for this is to provide for restoration of a histogram from e.g. file and allow for subsequent processing to continue to increment the histogram.For serialization / deserialization to / from a file I expected that serde. would be used in most cases. Do you have a use case where you can't use serde?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by davehadley** [comment]
Thanks for starting that pull request. It looks like your email reply got mangled by github?

> The use case for this is to provide for restoration of a histogram from e.g. file and allow for subsequent processing to continue to increment the histogram.

Is there a reason why you can't use serde for your use case?
